--------------INNER JOIN / JOIN--------------
SELECT * FROM STUDENTS INNER JOIN STU_DEPT ON STUDENTS.USN = STU_DEPT.USN;
SELECT * FROM STUDENTS S1 INNER JOIN STU_DEPT S2 ON S1.USN = S2.USN;


---------LEFT JOIN / LEFT OUTER JOIN--------------
SELECT * FROM STUDENTS S1 LEFT JOIN STU_DEPT S2 ON s1.usn = s2.usn;
SELECT * FROM STUDENTS S1 LEFT OUTER JOIN STU_DEPT S2 ON s1.usn = s2.usn;


---------RIGHT JOIN / RIGHT OUTER JOIN--------------
SELECT * FROM STUDENTS S1 RIGHT JOIN STU_DEPT S2 ON s1.usn = s2.usn;
SELECT * FROM STUDENTS S1 RIGHT OUTER JOIN STU_DEPT S2 ON s1.usn = s2.usn;
SELECT * FROM STUDENTS S1 RIGHT JOIN STU_DEPT S2 ON s1.usn = s2.usn WHERE PINCODE = 560076;

-------------------- FULL JOIN -----------------
SELECT * FROM STUDENTS FULL JOIN STU_DEPT ON STUDENTS.USN = STU_DEPT.USN;
SELECT * FROM STUDENTS S1 FULL OUTER JOIN STU_DEPT S2 ON S1.USN = S2.USN;


-------------------- NATURAL JOIN -----------------
SELECT * FROM STUDENTS NATURAL JOIN STU_DEPT;
SELECT * FROM STUDENTS NATURAL LEFT JOIN STU_DEPT;
SELECT * FROM STUDENTS NATURAL RIGHT JOIN STU_DEPT;
SELECT * FROM STUDENTS NATURAL FULL JOIN STU_DEPT;

-------------------- CROSS JOIN -----------------
SELECT * FROM STU_DEPT,STUDENTS ;
SELECT * FROM STU_DEPT CROSS JOIN STUDENTS ;

-------------------- SELF JOIN -----------------

SELECT S1.IDD, S2.IDD FROM STUDENTS S1, STUDENTS S2 WHERE S1.USN>S2.USN;


------SELECT MULTIPLE COLUMN FROM MULTIPLE TABLE WITHOUT JOINTS

SELECT S1.NAME, S1.USN, S2.CITY, S2.COURSE FROM STUDENTS S1 INNER JOIN STU_DEPT S2 
ON S1.USN=S2.USN WHERE S2.PINCODE>500000;


------- JOIN 3 TABLES ---------





