SELECT * FROM user_users;
SELECT * FROM all_users;

--CREATE USER tiple IDENTIFIED BY Shashank#123;



GRANT CREATE SESSION, GRANT ANY PRIVILEGE TO tiple;


--GRANT UNLIMITED TABLESPACE TO tiple;

drop user tiple;